import { Inter } from "next/font/google";
import "./globals.css";
import { Box, Container, Grid } from "@mui/material";
import Link from "next/link";
import DashboardLinks from "@/components/DashboardLinks/DashboardLinks";
import DensityMediumIcon from "@mui/icons-material/DensityMedium";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Container>
          <Grid container sx={{ marginTop: "4px", }} spacing={1}>
            <Grid
              item
              xs={12}
              sx={{
                backgroundColor: "black",
                height: "full",
                borderRadius: "5px",
              }}
              sm={4}
            >
              <DashboardLinks />
            </Grid>
            <Grid item xs={12} sm={8}>
              {children}
            </Grid>
          </Grid>
        </Container>
      </body>
    </html>
  );
}
